# Generated by Django 5.1.4 on 2025-02-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_cliente_cupos_cliente_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacts',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10),
        ),
    ]
